package edu.iit.sat.itmd4515.hanggrian.fp.controllers;

import edu.iit.sat.itmd4515.hanggrian.fp.db.Students;
import edu.iit.sat.itmd4515.hanggrian.fp.db.schemas.Student;
import jakarta.ejb.EJB;
import jakarta.enterprise.context.RequestScoped;
import jakarta.inject.Named;
import java.io.Serializable;
import java.util.List;
import java.util.stream.Collectors;

/**
 * The initial point of web application showing the IDs of student generated by the startup service.
 */
@Named("indexController")
@RequestScoped
public class IndexController implements Serializable {
    @EJB Students students;

    /**
     * Spread non-admin student records to collect their usernames as unordered list.
     */
    public List<String> getStudentIds() {
        return students
            .selectAllExceptAdmin()
            .stream()
            .map(Student::getStudentId)
            .collect(Collectors.toList());
    }
}
